openapi: 3.0.3
info:
  title: x402 Client Data Models
  description: Data specifications for the x402 Client Library models.
  version: 1.0.0
paths: {}
components:
  schemas:
    PaymentPayload:
      type: object
      description: The payload sent to verify and settle payments.
      properties:
        x402Version:
          type: integer
          example: 2
        payload:
          type: object
          description: Signed data (e.g., EIP-712 signature)
        accepted:
          $ref: '#/components/schemas/PaymentRequirements'
        resource:
          $ref: '#/components/schemas/ResourceInfo'
        extensions:
          type: object
          additionalProperties: true
    PaymentRequirements:
      type: object
      description: Requirements provided by the server that the client must fulfill.
      properties:
        scheme:
          type: string
          description: Payment scheme (e.g., "exact", "upto")
          example: "exact"
        network:
          type: string
          description: CAIP-2 network identifier (e.g., "eip155:1")
          example: "eip155:84532"
        asset:
          type: string
          description: Asset identifier (e.g., contract address or "native")
          example: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
        amount:
          type: string
          description: Payment amount (decimal string)
          example: "100000"
        payTo:
          type: string
          description: Recipient address
          example: "0xFacilitatorAddress..."
        maxTimeoutSeconds:
          type: integer
          example: 3600
        extra:
          type: object
          additionalProperties: true
    ResourceInfo:
      type: object
      description: Information about the resource being accessed.
      properties:
        url:
          type: string
          example: "https://api.example.com/premium-data"
        description:
          type: string
          example: "Premium Market Data"
        mimeType:
          type: string
          example: "application/json"
    PaymentHeader:
      type: string
      description: Base64 encoded PaymentPayload (PAYMENT-SIGNATURE)
      example: "ey...}"
    UnpaidResponse:
      type: object
      description: Body of 402 Payment Required response
      properties:
        error:
          type: string
          example: "Payment required for this resource"
        resource:
          $ref: '#/components/schemas/ResourceInfo'
        accepts:
          type: array
          items:
            $ref: '#/components/schemas/PaymentRequirements'
    SupportedResponse:
      type: object
      description: Response from Facilitator GET /supported
      properties:
        kinds:
          type: array
          items:
            $ref: '#/components/schemas/SupportedKind'
        extensions:
          type: array
          items:
            type: string
            example: "bazaar"
        signers:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
              example: "0xSignerAddress..."
          description: Map of CAIP network family to signer addresses
    SupportedKind:
      type: object
      properties:
        x402Version:
          type: integer
          example: 2
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "eip155:84532"
        extra:
          type: object
