openapi: 3.0.3
info:
  title: x402 Facilitator API
  description: API for the x402 Facilitator service which handles verification and settlement of payments.
  version: 1.0.0
servers:
  - url: http://localhost:4022
    description: Local development server
paths:
  /supported:
    get:
      summary: Get supported networks and schemes
      operationId: getSupported
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SupportedResponse'
  /verify:
    post:
      summary: Verify a payment signature
      operationId: verifyPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyRequest'
      responses:
        '200':
          description: Verification result (check isValid field)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /settle:
    post:
      summary: Settle a payment on-chain
      operationId: settlePayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SettleRequest'
      responses:
        '200':
          description: Settlement result (check success field)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SettleResponse'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
components:
  schemas:
    SupportedResponse:
      type: object
      properties:
        kinds:
          type: array
          items:
            $ref: '#/components/schemas/SupportedKind'
        extensions:
          type: array
          items:
            type: string
        signers:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Map of CAIP network family to signer addresses
    SupportedKind:
      type: object
      properties:
        x402Version:
          type: integer
          example: 2
        scheme:
          type: string
          example: exact
        network:
          type: string
          example: eip155:84532
        extra:
          type: object
          additionalProperties: true
    VerifyRequest:
      type: object
      required:
        - paymentPayload
        - paymentRequirements
      properties:
        paymentPayload:
          $ref: '#/components/schemas/PaymentPayload'
        paymentRequirements:
          $ref: '#/components/schemas/PaymentRequirements'
    VerifyResponse:
      type: object
      properties:
        isValid:
          type: boolean
        invalidReason:
          type: string
        payer:
          type: string
    SettleRequest:
      type: object
      required:
        - paymentPayload
        - paymentRequirements
      properties:
        paymentPayload:
          $ref: '#/components/schemas/PaymentPayload'
        paymentRequirements:
          $ref: '#/components/schemas/PaymentRequirements'
    SettleResponse:
      type: object
      properties:
        success:
          type: boolean
        errorReason:
          type: string
        payer:
          type: string
        transaction:
          type: string
        network:
          type: string
    PaymentPayload:
      oneOf:
        - $ref: '#/components/schemas/PaymentPayloadV2'
        - $ref: '#/components/schemas/PaymentPayloadV1'
    PaymentRequirements:
      oneOf:
        - $ref: '#/components/schemas/PaymentRequirementsV2'
        - $ref: '#/components/schemas/PaymentRequirementsV1'
    PaymentPayloadV2:
      type: object
      properties:
        x402Version:
          type: integer
          example: 2
        payload:
          type: object
          properties:
            type:
              type: string
              enum: [authorization, authorizationEip3009]
              description: "Type of authorization (EVM Exact Scheme)"
              example: "authorizationEip3009"
            signature:
              type: string
              example: "0x1234..."
            authorization:
              type: object
          additionalProperties: true
        accepted:
          $ref: '#/components/schemas/PaymentRequirementsV2'
        resource:
          $ref: '#/components/schemas/ResourceInfo'
        extensions:
          type: object
          additionalProperties: true
    PaymentPayloadV1:
      type: object
      properties:
        x402Version:
          type: integer
          example: 1
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "eip155:84532"
        payload:
          type: object
          properties:
            signature:
              type: string
              example: "0x5678..."
            authorization:
              type: object
          additionalProperties: true
    PaymentRequirementsV2:
      type: object
      properties:
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "eip155:84532"
        asset:
          type: string
          example: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
        amount:
          type: string
          example: "100000"
        payTo:
          type: string
          example: "0xFacilitatorAddress..."
        maxTimeoutSeconds:
          type: integer
          example: 3600
        extra:
          type: object
    PaymentRequirementsV1:
      type: object
      properties:
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "base-sepolia"
        asset:
          type: string
          example: "0x036CbD53842c5426634e7929541eC2318f3dCF7e"
        maxAmountRequired:
          type: string
          example: "100000"
        payTo:
          type: string
          example: "0xFacilitatorAddress..."
        maxTimeoutSeconds:
          type: integer
          example: 600
        extra:
          type: object
    ResourceInfo:
      type: object
      properties:
        url:
          type: string
          example: "https://api.example.com/premium-data"
        description:
          type: string
          example: "Premium Market Data"
        mimeType:
          type: string
          example: "application/json"
