openapi: 3.0.3
info:
  title: x402 Server Protocol API
  description: Specification of the x402 Payment Protocol headers and response structures for protected resources.
  version: 1.0.0
paths:
  /resource:
    get:
      summary: Example protected resource
      description: |
        Accessing this resource without payment returns 402 Payment Required.
        Accessing with a valid `PAYMENT-SIGNATURE` header returns the resource and a `PAYMENT-RESPONSE` settlement header.
      operationId: getProtectedResource
      parameters:
        - in: header
          name: PAYMENT-SIGNATURE
          schema:
            type: string
            description: Base64 encoded PaymentPayload (V2) or X-PAYMENT (V1)
          required: false
      responses:
        '200':
          description: Resource content (Payment accepted)
          headers:
            PAYMENT-RESPONSE:
              description: Base64 encoded JSON of SettleResponse schema
              schema:
                type: string
          content:
            application/json:
              schema:
                description: "The protected resource content (implementation specific)"
                type: object
                additionalProperties: true
            text/html:
              schema:
                type: string
            '*/*':
              schema:
                description: "Any other content type"
                type: string
                format: binary
        '402':
          description: Payment Required
          headers:
            PAYMENT-REQUIRED:
              description: Base64 encoded JSON of PaymentRequired schema
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentRequired'
            text/html:
              schema:
                type: string
                description: Paywall HTML for browsers
components:
  schemas:
    PaymentRequired:
      type: object
      required:
        - x402Version
        - resource
        - accepts
      properties:
        x402Version:
          type: integer
          example: 2
        error:
          type: string
          example: "Payment Required"
        resource:
          $ref: '#/components/schemas/ResourceInfo'
        accepts:
          type: array
          items:
            $ref: '#/components/schemas/PaymentRequirements'
        extensions:
          type: object
          additionalProperties: true
    PaymentRequirements:
      type: object
      properties:
        scheme:
          type: string
          example: "exact"
        network:
          type: string
          example: "eip155:84532"
        asset:
          type: string
          example: "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
        amount:
          type: string
          example: "100000"
        payTo:
          type: string
          example: "0xFacilitatorAddress..."
        maxTimeoutSeconds:
          type: integer
          example: 3600
        extra:
          type: object
    ResourceInfo:
      type: object
      properties:
        url:
          type: string
          example: "https://api.example.com/premium-data"
        description:
          type: string
          example: "Premium Market Data"
        mimeType:
          type: string
          example: "application/json"
    PaymentPayload:
      type: object
      properties:
        x402Version:
          type: integer
          example: 2
        payload:
          type: object
        accepted:
          $ref: '#/components/schemas/PaymentRequirements'
    SettleResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        errorReason:
          type: string
          example: ""
        payer:
          type: string
          example: "0xPayerAddress..."
        transaction:
          type: string
          example: "0xTransactionHash..."
        network:
          type: string
          example: "eip155:84532"
